/* variable constants that will be used within other files */

const CHANGE_SEARCHFIELD = "CHANGE_SEARCHFIELD";
const REQUEST_ROBOTS_PENDING = "REQUEST_ROBOTS_PENDING";
const REQUEST_ROBOTS_SUCCESS = "REQUEST_ROBOTS_SUCCESS";
const REQUEST_ROBOTS_FAILED = "REQUEST_ROBOTS_FAILED";

export {
  CHANGE_SEARCHFIELD,
  REQUEST_ROBOTS_PENDING,
  REQUEST_ROBOTS_SUCCESS,
  REQUEST_ROBOTS_FAILED,
};
